version: '3.8'
services:
  shopify-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      SHOPIFY_API_KEY: ${SHOPIFY_API_KEY}
      SHOPIFY_API_SECRET: ${SHOPIFY_API_SECRET}
      HOST: ${HOST}
      BACKEND_URL: ${BACKEND_URL}
      BACKEND_API_KEY: ${BACKEND_API_KEY}
      SCOPES: ${SCOPES:-read_orders,read_checkouts}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
